### ISSUE TITLE
Defer installation/upgrade until admin has logged in

### ISSUE THREAD

**Issue by lat9** [lat9/one_page_checkout#104]
Don't run the plugin's admin-level installation script until there's an admin signed in to view the message(s).

**Comment by drbyte** [comment]
One way to accomplish this in `init_checkout_one.php` might be to put a line like this near the top before any queries etc:

`if (empty($_SESSION['admin_id'])) return;`

(My point is: instead of wrapping the entire file's contents inside a huge `if` clause, just do a quick early `return` to have it ignore the rest of the file. Makes code easier to read and maintain later.)

**Comment by lat9** [comment]
Thanks, DrByte.  I see the value in that quick return, but after years of one-entry/one-exit per function being drilled into my head, I'm not sure I can "do it".
