### ISSUE TITLE
Sorry, but our expedited checkout process cannot be used.

### ISSUE THREAD

**Issue by jeking928** [lat9/one_page_checkout#179]
Zen Cart 1.5.6a
Template: an_upscale_boutique
OPC: 2.1.0-beta5

When checking out with an account or guest, I get "Sorry, but our expedited checkout process cannot be used."

From the console:
(anonymous) @ index.php?main_page=checkout_one:28
jquery.checkout_one.min.js?1552409819:5 Uncaught TypeError: jQuery(...).on is not a function
    at HTMLDocument.<anonymous> (jquery.checkout_one.min.js?1552409819:5)
    at HTMLDocument.<anonymous> (jscript_jquery.js:33)
    at Function.<anonymous> (jscript_jquery.js:33)
    at Function.each (jscript_jquery.js:27)
    at HTMLDocument.ready (jscript_jquery.js:33)

Error logs are attached
[myDEBUG-one_page_checkout-na-2019-03-16.zip](https://github.com/lat9/one_page_checkout/files/2973965/myDEBUG-one_page_checkout-na-2019-03-16.zip)

**Comment by lat9** [comment]
That's identifying that the template's `html_header.php` is not including a version of jQuery for _OPC_'s use.

**Comment by jeking928** [comment]
Is there a minimum required jQuery version?
I've used the default html_header.php, and get the same problem.

**Comment by lat9** [comment]
Is this an online site that you could give me (via direct email) a link to?

**Comment by jeking928** [comment]
Maybe this goes as a new issue, but wanted to post here first. One-Page now loads. Canada Post shipping displays along with FedEx.

Changing shipping options does not update order totals.
Confirm the Order button cannot be clicked.
No error in the console.
There is a warning regarding FedEx shipping but seems unrelated. It's version 1.6.7
PHP Warning: key() expects parameter 1 to be array, null given in /includes/modules/shipping/fedexwebservices.php on line 708.

**Comment by lat9** [comment]
The site's still got HTML validation issues.  I'm guessing that that's at least part of the problem. 

It's like the headerWrapper isn't properly closed, since contentMainWrapper and footerWrapper both show up as children of the headerWrapper when viewing the site via the console's "Inspector" tab.

**Comment by icogiev** [comment]
I am having the same issue my site is https://autofox.net, i removed every payment or shipping module from Payment Methods Requiring Confirmation as well Guest Checkout: Disallowed Credit Class Order-Totals list's.

There was no jquery in the installation so I added 3.4.1 but still no difference.

Thank you in addvance.

**Comment by icogiev** [comment]
I forgot to mention that there are no log erros in my situation.

**Comment by lat9** [comment]
Your site has no shipping or payment methods defined and those templates from themeforest tend to carve up various Zen Cart core files, altering the HTML selectors that _OPC_ expects.

I just added a product (quite difficult, BTW) to my cart and went to guest checkout.  There were neither shipping selections nor payment-method selections available.

**Comment by svr22** [comment]
I am having the same problem.  Sorry, but our expedited checkout process cannot be used. Click here to use our alternate checkout process.  is the message;  the error in the console is Object doesn't support property or method 'on' and this goes to the following code in jquery.checkout_one.js

    jQuery(document).on("keypress", ":input:not(textarea)", function(event) {
        return event.keyCode != 13;
    });
I am a total newbie in this type of scripting but I would appreciate any help.  the error log is attached. 
[one_page_checkout-2-2020-02-17.log](https://github.com/lat9/one_page_checkout/files/4215895/one_page_checkout-2-2020-02-17.log)

**Comment by lat9** [comment]
@svr22, what version of jQuery is in use?  Which browser?

**Comment by lat9** [comment]
Noting that the jQuery `.on` method was added in jQuery 1.7.  You'll probably need to update your abagon template's /common/html_header.php to load a more recent version of jQuery (currently at v3.4.1).

**Comment by svr22** [comment]
You are genius.  I tried to upgrade to the new version of jquery based on
one of your suggestions at git-hub,  but missed calling the new jquery at
the html_header.  This is all really new to me.  I just ran an order and it
is a beautiful layout.  Thank you sooooo much.

 I do have one question.  The check and moneyorder payment option does not
work on the OPC, but it is fine in the account style checkout.  I am afraid
I might have messed up something because I have been wading deep into the
files for several days... Any ideas?

Sincerely,

Sandra van Riper

**Comment by lat9** [comment]
Sandra, that's a setting in the admin's **_One-Page Checkout_** configuration.  I've got that disabled on installation, since the `moneyorder` payment method could be prone to script-kiddie 'attacks', but it's your store and thus your choice.

**Comment by svr22** [comment]
Got it.... thanks again.  Can I pay you for your help????

Sincerely,

Sandra van Riper

**Comment by lat9** [comment]
Sure (and thanks for asking): https://www.paypal.me/lat9vinos?locale.x=en_US

BTW, welcome to GitHub!

**Comment by jfigure** [comment]
Hello Cindy,

I have the same problem since I added OPC to my test site. In addition to the "Sorry, but our expedited checkout process..." message, I have a pop-up message reading "Please contact the store owner; some required elements of this page are missing." When I click the OK button on the message, everything turned to be alright (A complete OPC page appeared) but otherwise, the page remains blank.
I checked the html_header.php file in templates/bootstrap/common folder and confirmed that the file calls jquery-3.7.1.min.js. The site is implemented with Bootstrap 3. 7. 0. Could you give me a hint what else I can look at? 

Thank you. 
Koichi

**Comment by lat9** [comment]
This topic is now covered in [this](https://github.com/lat9/one_page_checkout/wiki/Troubleshooting#some-required-elements-on-this-page-are-missing) GitHub Wiki article; check the browser's console-log and it will identify what information is missing.

**Comment by jfigure** [comment]
Thank you. The Chrome consoles says, "Missing #ottotal > div:first-child".  Based your post #1893 in the OPC Support Thread, I changed the code in jscript_main.php as follows; 
 "define('CHECKOUT_ONE_OTTOTAL_SELECTOR', '#ottotal > .ot-text');"
But still console keep saying "Missing #ottotal > div:first-child". I got stuck.
If it is so complicated, I can live with the multi-page checkout.

Best regards,
Koichi

**Comment by lat9** [comment]
Koichi, it sounds like you've got a downlevel version of OPC; that CHECKOUT_ONE_OTTOTAL_SELECTOR was removed in v2.5.2, although I _do_ still need to remove that definition from jscript_main.php.  Make sure that your jquery.checkout_one.js and jquery.checkout_one.min.js files are both 'up to level'.

Note that for OPC versions _prior to_ 2.5.2, that's a configuration setting, which is why changing that definition didn't do anything.

**Comment by jfigure** [comment]
Cindy, thank you. OPC works now! Finally I noticed the configuration setting on Admin and it's so easy to change the definition there! 

Best regards from Tokyo.
Koichi
