### ISSUE TITLE
Add TEXT_OPTION_DIVIDER to checkout page

### ISSUE THREAD

**Issue by simon1066** [lat9/one_page_checkout#213]
index.php?main_page=checkout_one 

On the above page (in the Shopping Cart Contents block) the separator between the attribute name and attribute value is defined as a colon in templates/tpl_modules_opc_shopping_cart.php line #46 

`              <li><?php echo $order->products[$i]['attributes'][$j]['option'] . ': ' . nl2br(zen_output_string_protected($order->products[$i]['attributes'][$j]['value'])); ?></li>
`

As this separator is defined elsewhere throughout the ZC code by `TEXT_OPTION_DIVIDER` I suggest that, to maintain consistency, line #46  is amended to

` <li><?php echo $order->products[$i]['attributes'][$j]['option'] . TEXT_OPTION_DIVIDER . nl2br(zen_output_string_protected($order->products[$i]['attributes'][$j]['value'])); ?></li>`

and that `define('TEXT_OPTION_DIVIDER', '&nbsp;-&nbsp;');` (the hyphen is the default across ZC code) is added to an appropriate language file (although I'm unable to identify which one is preferable).

**Comment by lat9** [comment]
Noting that, since that constant is used in multiple places (shopping cart and account-history-info), I'm _assuming_ that the constant will eventually be defined in the base Zen Cart's root-language file (e.g. english.php).

As such, I'll provide an in-code definition if that's not currently defined.
