### ISSUE TITLE
zc157 inter-operation, login page's form's name was changed

### ISSUE THREAD

**Issue by dbltoe** [lat9/one_page_checkout#260]
After about the fifth setup, I discovered that UltraCompare was giving me a glitch and not properly updating an OPC file.

I can now say that I have a beta with mod list and OPC being the only mods (other than Display Logs installed from the new Plugins Manager).

All works exactly as advertised UNLESS Guest Checkout is set to true.

With Guest Checkout set to true, clicking on Log In from the home page, an uncaught error shows in the console.
~~ Also, clicking on Place Order in the Customers portion of the admin results in the "Whoops, your session has expired."~~

OPC debug is on but no error appears in the logs.

Just a WAG but, I think it may be in the way the body tag is generated for the login page.

Sorry I can't be of more help than that.  Can easily grant access to the site if needed for testing.

**Comment by dbltoe** [comment]
Found out more info that is actually causing the Whoops.  I has nothing to do with OPC or it's Guest Checkout
[https://github.com/zencart/zencart/issues/3587](url)

Still have the uncaught error if Guest Checkout is true and Log In is clicked.

**Comment by lat9** [comment]
That uncaught error on the OPC login page is due to [this](https://github.com/zencart/zencart/commit/a9d8b73bb9787bb741c4eb8ca1d0b835d9c69744#diff-e3976b897ea1fcaf569b57709acfb7ca) change in form names for zc157.

All _prior_ versions of Zen Cart named that form `login`, while zc157 now names it `loginForm`.

Let me consider how best to support this zc157 change.

**Comment by dbltoe** [comment]
Have the test site with the situation available if needed.

**Comment by lat9** [comment]
Thanks, I've replicated the issue locally.
