### ISSUE TITLE
zencart 1.5.6c   Unable to pay 

### ISSUE THREAD

**Issue by 361579254** [lat9/one_page_checkout#266]
zencart 1.5.6c   install  one_page_checkout-2.1.0  And make necessary modification according to the document requirements
click confirm order  ,page show  json data 
![image](https://user-images.githubusercontent.com/16127750/89405189-bf4a6980-d74d-11ea-8255-511c873ef96b.png)
![image](https://user-images.githubusercontent.com/16127750/89405248-d4bf9380-d74d-11ea-8817-1dca2fb0870b.png)
This is a link to the website
https://www.fancynewlly.com/
Please also help to see what causes, thank you!

**Comment by lat9** [comment]
Why are you using a woefully old version of _OPC_?  Try using the current version &mdash; v2.3.3.

I don't hold much hope, by the way, given that your site's template is a ThemeForest one and the jQuery version in use on the site (1.12.2) is also very oldy-moldy.

**Comment by 361579254** [comment]
> 为什么使用的是旧版本的_OPC_？尝试使用当前版本-v2.3.3。
> 
> 顺便说一句，鉴于您网站的模板是ThemeForest模板，并且网站上使用的jQuery版本（1.12.2）也非常老旧，因此我希望不高。

After using OPC v2.3.3, the effect is the same as before, and the jQuery version is upgraded to v2.2.4. I am helpless. Please help me

**Comment by 361579254** [comment]
> Why are you using a woefully old version of _OPC_? Try using the current version — v2.3.3.
> 
> I don't hold much hope, by the way, given that your site's template is a ThemeForest one and the jQuery version in use on the site (1.12.2) is also very oldy-moldy.

After using OPC v2.3.3, the effect is the same as before, and the jQuery version is upgraded to v2.2.4. I am helpless. Please help me

**Comment by lat9** [comment]
I'm seeing the following console log, indicating that there's something amiss in the value returned:

![image](https://user-images.githubusercontent.com/2685585/89525385-184ce880-d7b4-11ea-87e3-a9d78c911a76.png)
... and, looking at the response text:

![image](https://user-images.githubusercontent.com/2685585/89525712-9c9f6b80-d7b4-11ea-8d46-51efb449abd7.png)
... you can see that invalid character, a [Byte-Order-Mark/BOM](https://www.w3.org/International/questions/qa-byte-order-mark) at the start of the data.

I believe that one or more of your site's .php files has been saved as UTF8-BOM instead of UTF8 and that's causing that unwanted output.
