### ISSUE TITLE
Add notification to enable override of OPC's enabled status.

### ISSUE THREAD

**Issue by proseLA** [lat9/one_page_checkout#402]
i am trying to override whether OPC is enabled or not.  which i think is this line here:

https://github.com/lat9/one_page_checkout/blob/5ab4b005d480cf5868ae0932e6f6a059b3dd8e21/includes/classes/OnePageCheckout.php#L155

now, i have added an observer, and changed the visibility of `$isEnabled` to public, and then within my observer, i have tried adding the following code:
```
$class->isEnabled = false;
$_SESSION['opc']->isEnabled = false;
```
and i know both lines of code are getting hit, as the function will return false; and yet OPC stays enabled.

and yet if i change line 155 referenced above to:

```
$this->isEnabled = false;
return $this->isEnabled;
```
OPC is now not enabled.

what might i be doing wrong?

i would like to add an observer to disable OPC; and yet it seems i am somehow unable to do this task.

**Comment by lat9** [comment]
Right, I'll need to add a notification in the following section, after the overall check for `CHECKOUT_ONE_ENABLED`, to enable an observer to provide that override.

**Comment by lat9** [comment]
Also, see this section of the [Wiki](https://github.com/lat9/one_page_checkout/wiki/Notifications-Issued#set-disabled).

**Comment by proseLA** [comment]
ok, so it is a load order thing...  interesting...

is there a reason why one prefers using a new var as opposed to changing the visibility of `$isEnabled`?

and is it worth wild having a conversation on the ZC repo about moving the auto loading observer class higher up the hierarchy?  or has that conversation already been had, and i missed it?

**Comment by lat9** [comment]
The notification vs. a public function to control the enabling is based on follow-on (i.e. in the field) support required.  As it is, the session-based `opc` class is loaded/instantiated just after the session's created at CP 75 and the observer comes in at CP 97 so that it can respond to requests for `zen_in_guest_checkout` that happen early in the load-process.  Allowing a separate method to directly control OPC's status could be a right booger to support.

Looking at the [history](https://github.com/lat9/one_page_checkout/commits/master/includes/auto_loaders/config.checkout_one.php) for the auto-loader, it started out at CP 200 and then moved further lower in the auto-load sequence to handle the above requests as well as 'early` calls to `zen_is_logged_in` and `zen_in_guest_checkout`..

**Comment by proseLA** [comment]
i am looking at this yet again.  i think for the most useful use of an observer is to allow the observer to enable or disable OPC.  i can see the benefit of being able to do it both ways...  maybe it is an edge case that a shop would want 3 page checkout as the standard and only enable OPC for certain situations, but why not allow people to do that?

your last explanation did not help me understand why the visibility of `$isEnabled` is protected.  by changing it to public, one could then use `$class->isEnabled = false;` in the observer to change the var.  i get it that the observer needs to be loaded earlier than an auto loading observer; so thank you for answering that.  but i'm still not sure why adding a new var (`$setDisabled`) is preferably to changing the visibility of the existing var.

that said, i have no problem with that methodology of creating a new var and passing that to the observer, but i still  feel if we are adding an observer to control OPC's status, we should be able to turn it off OR on.

**Comment by lat9** [comment]
It's primarily that the OPC class is a state-machine and if the status changed from enabled to disabled at random times that would potentially cause unwanted and very-difficult-to-support issues.
